# Generated by Django 3.1.3 on 2020-11-16 13:28

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('account_manager', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Account',
            fields=[
                ('account_no', models.CharField(max_length=10, primary_key=True, serialize=False)),
                ('customer_name', models.CharField(max_length=50)),
                ('contact_info', models.CharField(max_length=20)),
                ('customer_type', models.CharField(max_length=20)),
                ('start_date', models.DateField()),
                ('end_date', models.DateField()),
                ('total_amount', models.FloatField()),
                ('account_mgr', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='account', to='account_manager.accountmanager')),
            ],
            options={
                'db_table': 'accounts',
            },
        ),
    ]
