# Generated by Django 3.1.3 on 2020-11-16 12:38

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Personnel',
            fields=[
                ('pid', models.CharField(max_length=10, primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=50)),
                ('email', models.EmailField(editable=False, max_length=254, unique=True)),
                ('address', models.CharField(max_length=100)),
                ('supervisor_pid', models.CharField(max_length=10, null=True)),
            ],
            options={
                'db_table': 'personnel',
            },
        ),
    ]
