# Generated by Django 3.1.3 on 2020-11-16 13:04

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('personnel', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='AccountManager',
            fields=[
                ('pid', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, primary_key=True, related_name='account_managers', serialize=False, to='personnel.personnel')),
                ('manager_title', models.CharField(max_length=20)),
                ('office_location', models.CharField(max_length=100)),
            ],
            options={
                'db_table': 'account_managers',
            },
        ),
    ]
