# Generated by Django 3.1.3 on 2020-11-16 13:09

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Truck',
            fields=[
                ('truck_id', models.CharField(max_length=20, primary_key=True, serialize=False)),
                ('model', models.CharField(max_length=50)),
                ('truck_type', models.CharField(max_length=50)),
            ],
            options={
                'db_table': 'trucks',
            },
        ),
    ]
